name: shipping
description: Shipping and logistics service
version: 0.1.0

environment:
  sdk: ^3.2.0

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  redis: ^2.2.0
  json_annotation: ^4.8.1
  uuid: ^4.2.2

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
